"""Configuration: constants and prompt templates."""

from .constants import (
    BASE_DIR, DATA_DIR, FLAT_DIR, RAW_FHIR_GLOB,
    CLAIMS_CHROMA_DIR, PDF_CHROMA_DIR,
    EMBED_MODEL, CLAIMS_LLM_MODEL, PDF_LLM_MODEL, ROUTER_MODEL,
    PDF_TOP_K, CLAIMS_TOP_K, MAX_CHUNK_CHARS, HISTORY_TURNS,
    ROUTER_KWARGS, CHECKPOINT_DB, CHUNK_SIZE, CHUNK_OVERLAP, WRITE_JSONL,
)
from .prompts import ROUTER_PROMPT, CLAIMS_ASSIST_SYSTEM, BENEFITS_TEMPLATE

__all__ = [
    # constants
    "BASE_DIR", "DATA_DIR", "FLAT_DIR", "RAW_FHIR_GLOB",
    "CLAIMS_CHROMA_DIR", "PDF_CHROMA_DIR",
    "EMBED_MODEL", "CLAIMS_LLM_MODEL", "PDF_LLM_MODEL", "ROUTER_MODEL",
    "PDF_TOP_K", "CLAIMS_TOP_K", "MAX_CHUNK_CHARS", "HISTORY_TURNS",
    "ROUTER_KWARGS", "CHECKPOINT_DB", "CHUNK_SIZE", "CHUNK_OVERLAP", "WRITE_JSONL",
    # prompts
    "ROUTER_PROMPT", "CLAIMS_ASSIST_SYSTEM", "BENEFITS_TEMPLATE",
]
